version: '2'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    hostname: artifactory
    ports:
      - '8081:8081'
    volumes:
      - ./data/var/opt/jfrog/artifactory/backup:/var/opt/jfrog/artifactory/backup:rw
      - ./data/var/opt/jfrog/artifactory/data:/var/opt/jfrog/artifactory/data:rw
      - ./data/var/opt/jfrog/artifactory/logs:/var/opt/jfrog/artifactory/logs:rw
      - ./data/var/opt/jfrog/artifactory/etc:/var/opt/jfrog/artifactory/etc:rw
